version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - ls -la
      - echo installing "node modules"
      - npm install

  pre_build:
    commands:
      - echo installing source npm dependencies ...
      - npm run build
      - ls -la

  post_build:
    commands:
      - echo deployment completed on `date`

artifacts:
    files:
      - '**/*'
    base-directory: 'build'  