version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - ls -la
      - echo installing "node modules"
      - npm install

  pre_build:
    commands:
      - echo Logging into Amazon ECR ...
      - echo $AWS_DEFAULT_REGION
      - echo $IMAGE_REPO_NAME
      - echo $AWS_ACCOUNT_ID
      - echo aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo installing source npm dependencies ...
      - npm run build
      - ls -la

  post_build:
    commands:
      - echo deployment completed on `date`

artifacts:
    files:
      - '**/*'
    base-directory: 'build'  