front_end_repo_id              = "GrowHydro/frontend-cd-ci-pipe"
repo_branch_name               = "main"
company                        = "homegrown-hydro"
dockerhub_credentials          = "arn:aws:secretsmanager:us-west-2:373157733381:secret:prod/growroom/backend-kJO4iV"
codestar_connector_credentials = "arn:aws:codestar-connections:us-east-1:373157733381:connection/bf25d462-316e-4fae-8ab6-c7801fb32667"
pipeline_bucket_name           = "home-grown-hydo-artifact-bucket-build"
env                            = "prod"
